### ISSUE TITLE
Normalized weights in computation of Z

### ISSUE THREAD

**Issue by willemvandenboom** [particlemontecarlo/unbiased_pimh#2]
Thank you for posting the code to reproduce the results from your paper! While going over it, I wondered the following:
https://github.com/particlemontecarlo/unbiased_pimh/blob/f89d7b0210ad5ae98d21c4c6cffad4df22b4e1e1/R/CPF.R#L204
includes the normalized weights (specifically their logs `log_W`) in the computation of `log_weights` and thus ultimately `logz = sum(lognormalising)`. However, the definition of *Z* in Section B.1 of [your paper](http://proceedings.mlr.press/v89/middleton19a.html) only includes *w*, not the normalized *W*.
It seems to me that `log_w` and `inc_w()` correspond with the log of *w* in the paper.

Am I correct that there is a discrepancy between the description of *Z* in the paper and `log_z` for SMC in the code?

**Comment by particlemontecarlo** [comment]
Hi Willem - thanks for getting in touch! And good question!

I've been back through the code - I think the issue you raise is ok though
I'm now concerned with another aspect of the implementation.

Briefly, we would expect log_W to appear in the recursion of log_Z as per
Equation (14) in Del Moral, Pierre, Arnaud Doucet, and Ajay Jasra.
"Sequential monte carlo samplers." *Journal of the Royal Statistical
Society: Series B (Statistical Methodology)* 68.3 (2006): 411-436.

That being said, on closer inspection I'm now no longer convinced the
implementation is correctly handling the initial conditions of the
algorithm correctly, though I need to look more into this.

I will get back to you with a more detailed reply in due course, though
your question is greatly appreciated.

Very best,

Lawrence

**Comment by willemvandenboom** [comment]
Ah, I missed that you set `log_W` to a constant value whenever resampling in
https://github.com/particlemontecarlo/unbiased_pimh/blob/f89d7b0210ad5ae98d21c4c6cffad4df22b4e1e1/R/CPF.R#L218
As such, the code is indeed consistent with the special case of resampling at each time step that you discuss in the paper.
Thank you for looking into this!
